spring:
  application:
    name: ktharaspiservice
ktha:
  system:
    homeServerEndpoint: http://arah.home.kawumtech.de:8080
    timeoutBetweenReads: 3000
  sensors:
    ds1820:
      testSensor01:
        sensorBaseDirectory: /sys/bus/w1/devices
        sensorHardwareId: 10-000802f954a2
#      testSensor02: 
#        sensorBaseDirectory: /sys/bus/w1/devices
#        sensorHardwareId: 10-000802f954a3
#    mcp3008:
#      testSensor03:
#        pin: 0
#        spiChannel: CS0
#        sensorType: ANALOG
  actuators:
    rcswitch:
      testRc01:
        pin: 4
        switchGroup: '00101'
        switchCode: 1
    pwm:
      pwm_r: 
        pin: 23
        maxValue: 100
      pwm_g: 
        pin: 24
        maxValue: 100
      pwm_b:
        pin: 22
        maxValue: 100
    gpio:
      testGpio01:
        pin: 29
